In [1]:
import os
import glob
from collections import OrderedDict

import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

from scipy import io as sio
from sklearn.decomposition import PCA

from keras.utils import np_utils
from keras.models import load_model

# TCN imports 
import tf_models, ap_datasets, utils, metrics
from utils import imshow_

Using TensorFlow backend.


In [2]:
split = 'Split_01'
base_dir = "/home/jinchoi/src/rehab/dataset/action/UCF101/"

model = load_model('../models/AP-TCN_v0.3_UCF101_{0}.h5'.format(split))
max_len = 90

X_test = np.load(base_dir + 'AlexNet-fc7-npy/X_test_ucf_' + split + '.npy');
y_test = np.load(base_dir + 'AlexNet-fc7-npy/y_test_ucf_' + split + '.npy');

y_test_ = [np.array([y_test[i]]) for i in range(len(y_test))]
X_test_m, M_test = utils.mask_data_one_tensor(X_test, max_len, mask_value=-1)

In [35]:
print("Prediction on test data...")
AP_test = model.predict(X_test_m, verbose=0)
P_test = [p.argmax(1)+1 for p in AP_test]

# get the test accuracy 
cnt = 0
for i in range(len(P_test)):
    if P_test[i][0] == y_test_[i][0]:
        cnt += 1
accuracy = float(cnt)/len(P_test)
print 'Test accuracy on {0}: {1}'.format(split, accuracy)

Prediction on test data...
Test accuracy on Split_01: 0.867036743325


In [18]:
P_test = [np.argmax(p)+1 for p in AP_test]
P_test
# get the test accuracy 
cnt = 0
for i in range(len(P_test)):
    if P_test[i] == y_test_[i][0]:
        cnt += 1
accuracy = float(cnt)/len(P_test)
print 'Test accuracy on {0}: {1}'.format(split, accuracy)

Test accuracy on Split_01: 0.867036743325


In [40]:
P_test = [np.argmax(p)+1 for p in AP_test]


In [44]:
tmp = (y_test==P_test)

In [50]:
y_test

array([  1,   1,   1, ..., 101, 101, 101])

In [69]:
### Evaluate accuracy on the random permuted test data

rand_ind=np.random.permutation(len(X_test_m))
X_test_m_shuffle = X_test_m[rand_ind,:,:]
y_test_shuffle = [np.array([y_test[rand_ind[i]]]) for i in range(len(y_test))]

print("Prediction on test data...")
AP_test = model.predict(X_test_m_shuffle, verbose=0)
P_test = [p.argmax(1)+1 for p in AP_test]

# get the test accuracy 
cnt = 0
for i in range(len(P_test)):
    if P_test[i][0] == y_test_shuffle[i][0]:
        cnt += 1
accuracy = float(cnt)/len(P_test)
print 'Test accuracy on {0}: {1}'.format(split, accuracy)

Prediction on test data...
Test accuracy on Split_01: 0.867036743325


In [52]:
# get the test accuracy 
cnt = 0
for i in range(len(P_test)):
    if P_test[i][0] == y_test_[i][0]:
        cnt += 1
accuracy = float(cnt)/len(P_test)
print 'Test accuracy on {0}: {1}'.format(split, accuracy)

Test accuracy on Split_01: 0.00951625693894


In [99]:
P_test = [np.argmax(p)+1 for p in AP_test]
y_test_shuffle = y_test[rand_ind.tolist()]
tmp = (y_test_shuffle==P_test)
float(np.sum(tmp))/len(y_test)

0.8670367433254031

In [92]:
P_test

[60,
 36,
 12,
 4,
 57,
 47,
 8,
 27,
 61,
 14,
 12,
 61,
 35,
 67,
 24,
 50,
 3,
 20,
 61,
 90,
 85,
 83,
 57,
 48,
 57,
 21,
 89,
 12,
 62,
 24,
 19,
 19,
 45,
 42,
 61,
 62,
 39,
 12,
 87,
 34,
 88,
 5,
 36,
 48,
 42,
 36,
 9,
 55,
 47,
 30,
 42,
 33,
 78,
 36,
 88,
 57,
 82,
 23,
 88,
 22,
 23,
 85,
 7,
 37,
 4,
 41,
 46,
 63,
 72,
 50,
 73,
 47,
 63,
 56,
 76,
 34,
 91,
 50,
 69,
 62,
 37,
 16,
 63,
 55,
 31,
 87,
 54,
 61,
 10,
 21,
 7,
 69,
 8,
 5,
 49,
 24,
 5,
 3,
 3,
 18,
 23,
 52,
 1,
 52,
 42,
 37,
 39,
 60,
 88,
 50,
 77,
 9,
 80,
 49,
 90,
 64,
 17,
 45,
 57,
 82,
 57,
 62,
 17,
 86,
 36,
 70,
 87,
 57,
 20,
 76,
 52,
 74,
 73,
 67,
 48,
 3,
 54,
 49,
 53,
 31,
 50,
 27,
 13,
 68,
 66,
 53,
 59,
 76,
 12,
 31,
 65,
 47,
 24,
 77,
 17,
 32,
 48,
 4,
 59,
 30,
 37,
 39,
 49,
 32,
 16,
 3,
 42,
 62,
 1,
 89,
 26,
 36,
 10,
 49,
 59,
 67,
 85,
 60,
 27,
 41,
 73,
 91,
 16,
 15,
 80,
 72,
 57,
 50,
 15,
 54,
 40,
 10,
 2,
 3,
 21,
 79,
 36,
 21,
 24,
 4,
 77,
 46,
 74,
 83,
 4

In [93]:
y_test_shuffle 

array([60, 92, 12, ..., 97, 97,  5])

In [94]:
tmp

array([ True, False,  True, ..., False, False,  True], dtype=bool)

In [95]:
np.sum(tmp)

3280

In [96]:
len(y_test)

3783

In [98]:
float(np.sum(tmp))/len(y_test)

0.8670367433254031